spring.application.name=glasseshop

server.port=8081

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SWP-Glasses;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# VNPAY Properties
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:5173/payment-result
vnpay.tmnCode=8CVCL0QE
vnpay.secretKey=FSLP4TXRVF5MJHQ3QYAPGFWCYH3NOZOP
vnpay.version=2.1.0
vnpay.command=pay